/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elementosvisuales;

/**
 *
 * @author jorge
 */
public class Elementosvisuales extends javax.swing.JFrame {

    /**
     * Creates new form Elementosvisuales
     */
    public Elementosvisuales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSeleccion = new javax.swing.JTextField();
        Mnbarra = new javax.swing.JMenuBar();
        Mnadministrador = new javax.swing.JMenu();
        MnIguardar = new javax.swing.JMenuItem();
        MnInuevo = new javax.swing.JMenuItem();
        Mnuser = new javax.swing.JMenu();
        MnInuevousuario = new javax.swing.JMenuItem();
        MnIbuscarusuario = new javax.swing.JMenuItem();
        MneditarUsuario = new javax.swing.JMenu();
        MnICambiarN = new javax.swing.JMenuItem();
        MnICaracteristicas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSeleccion.setText(" ");

        Mnadministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admin.png"))); // NOI18N
        Mnadministrador.setText("administrador");
        Mnadministrador.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Mnadministrador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mnadministrador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Mnadministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnadministradorActionPerformed(evt);
            }
        });

        MnIguardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MnIguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        MnIguardar.setText("Guardar");
        MnIguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnIguardarActionPerformed(evt);
            }
        });
        Mnadministrador.add(MnIguardar);

        MnInuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MnInuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/new.png"))); // NOI18N
        MnInuevo.setText("Nuevo");
        MnInuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnInuevoActionPerformed(evt);
            }
        });
        Mnadministrador.add(MnInuevo);

        Mnbarra.add(Mnadministrador);

        Mnuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        Mnuser.setText("usuario");
        Mnuser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mnuser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        MnInuevousuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnInuevousuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        MnInuevousuario.setText("Nuevo Usuari");
        MnInuevousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnInuevousuarioActionPerformed(evt);
            }
        });
        Mnuser.add(MnInuevousuario);

        MnIbuscarusuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnIbuscarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update.png"))); // NOI18N
        MnIbuscarusuario.setText("Buscar Usuario");
        MnIbuscarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnIbuscarusuarioActionPerformed(evt);
            }
        });
        Mnuser.add(MnIbuscarusuario);

        MneditarUsuario.setText("Editar");

        MnICambiarN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnICambiarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardarN.png"))); // NOI18N
        MnICambiarN.setText("Cambiar nombre");
        MnICambiarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnICambiarNActionPerformed(evt);
            }
        });
        MneditarUsuario.add(MnICambiarN);

        MnICaracteristicas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnICaracteristicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documents_folder.png"))); // NOI18N
        MnICaracteristicas.setText("Editar caracteristicas");
        MnICaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnICaracteristicasActionPerformed(evt);
            }
        });
        MneditarUsuario.add(MnICaracteristicas);

        Mnuser.add(MneditarUsuario);

        Mnbarra.add(Mnuser);

        setJMenuBar(Mnbarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(txtSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(txtSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnInuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnInuevoActionPerformed
 
     txtSeleccion.setText("nuevo");
    }//GEN-LAST:event_MnInuevoActionPerformed

    private void MnIguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnIguardarActionPerformed
      txtSeleccion.setText("guardado");

    }//GEN-LAST:event_MnIguardarActionPerformed

    private void MnadministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnadministradorActionPerformed
         txtSeleccion.setText("administrador");

    }//GEN-LAST:event_MnadministradorActionPerformed

    private void MnInuevousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnInuevousuarioActionPerformed
          txtSeleccion.setText(" Nuevo usuario");

    }//GEN-LAST:event_MnInuevousuarioActionPerformed

    private void MnIbuscarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnIbuscarusuarioActionPerformed
            txtSeleccion.setText(" Buscar usuario");

    }//GEN-LAST:event_MnIbuscarusuarioActionPerformed

    private void MnICambiarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnICambiarNActionPerformed
             txtSeleccion.setText(" cambiar");

    }//GEN-LAST:event_MnICambiarNActionPerformed

    private void MnICaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnICaracteristicasActionPerformed
              txtSeleccion.setText(" carcateristicas");

    }//GEN-LAST:event_MnICaracteristicasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elementosvisuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elementosvisuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elementosvisuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elementosvisuales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elementosvisuales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnICambiarN;
    private javax.swing.JMenuItem MnICaracteristicas;
    private javax.swing.JMenuItem MnIbuscarusuario;
    private javax.swing.JMenuItem MnIguardar;
    private javax.swing.JMenuItem MnInuevo;
    private javax.swing.JMenuItem MnInuevousuario;
    private javax.swing.JMenu Mnadministrador;
    private javax.swing.JMenuBar Mnbarra;
    private javax.swing.JMenu MneditarUsuario;
    private javax.swing.JMenu Mnuser;
    private javax.swing.JTextField txtSeleccion;
    // End of variables declaration//GEN-END:variables
}
