/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elementosvisuales;

/**
 *
 * @author jorge
 */
public class menus extends javax.swing.JFrame {

    /**
     * Creates new form menus
     */
    public menus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXTSeleccioon = new javax.swing.JTextField();
        MNbarra = new javax.swing.JMenuBar();
        Mnacrhivo = new javax.swing.JMenu();
        MnIAbrir = new javax.swing.JMenuItem();
        MnCerrar = new javax.swing.JMenuItem();
        MnReciente = new javax.swing.JMenu();
        MnIArchivo1 = new javax.swing.JMenuItem();
        MnIarchivo2 = new javax.swing.JMenuItem();
        Mnediccion = new javax.swing.JMenu();
        MnCopiar = new javax.swing.JMenuItem();
        Mnpegar = new javax.swing.JMenuItem();
        MnCortar = new javax.swing.JMenuItem();
        MnRdbNegritas = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TXTSeleccioon.setText(" ");

        Mnacrhivo.setText("Archivo");

        MnIAbrir.setText("Abrir");
        MnIAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnIAbrirActionPerformed(evt);
            }
        });
        Mnacrhivo.add(MnIAbrir);

        MnCerrar.setText("Cerrar");
        Mnacrhivo.add(MnCerrar);

        MnReciente.setText("Recientes");

        MnIArchivo1.setText("Archivo1");
        MnIArchivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnIArchivo1ActionPerformed(evt);
            }
        });
        MnReciente.add(MnIArchivo1);

        MnIarchivo2.setText("Archivo2");
        MnIarchivo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnIarchivo2ActionPerformed(evt);
            }
        });
        MnReciente.add(MnIarchivo2);

        Mnacrhivo.add(MnReciente);

        MNbarra.add(Mnacrhivo);

        Mnediccion.setText("Edicion");

        MnCopiar.setText("copiar");
        MnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCopiarActionPerformed(evt);
            }
        });
        Mnediccion.add(MnCopiar);

        Mnpegar.setText("Pegar");
        Mnpegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnpegarActionPerformed(evt);
            }
        });
        Mnediccion.add(Mnpegar);

        MnCortar.setText("Cortar");
        MnCortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCortarActionPerformed(evt);
            }
        });
        Mnediccion.add(MnCortar);

        MnRdbNegritas.setText("Negritas");
        MnRdbNegritas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRdbNegritasActionPerformed(evt);
            }
        });
        Mnediccion.add(MnRdbNegritas);

        MNbarra.add(Mnediccion);

        setJMenuBar(MNbarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(TXTSeleccioon, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(TXTSeleccioon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnIAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnIAbrirActionPerformed
      TXTSeleccioon.setText("archivo->abrir");

    }//GEN-LAST:event_MnIAbrirActionPerformed

    private void MnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCopiarActionPerformed
       TXTSeleccioon.setText("ediccion->copiar");

    }//GEN-LAST:event_MnCopiarActionPerformed

    private void MnpegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnpegarActionPerformed
   TXTSeleccioon.setText("ediccion->pegar");
    }//GEN-LAST:event_MnpegarActionPerformed

    private void MnCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCortarActionPerformed
    TXTSeleccioon.setText("ediccion->cortar"); 
    }//GEN-LAST:event_MnCortarActionPerformed

    private void MnIArchivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnIArchivo1ActionPerformed
     TXTSeleccioon.setText("Archivo->Abrir Recientes ->Archivo1"); 

    }//GEN-LAST:event_MnIArchivo1ActionPerformed

    private void MnIarchivo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnIarchivo2ActionPerformed
      TXTSeleccioon.setText("Archivo->Abrir Recientes ->Archivo2"); 
    }//GEN-LAST:event_MnIarchivo2ActionPerformed

    private void MnRdbNegritasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRdbNegritasActionPerformed
   if(MnRdbNegritas.isSelected()){
       TXTSeleccioon.setText("Ediccion-->Habilitar N");
       }
   else{ TXTSeleccioon.setText("Ediccion--> Desabilitar N");
   }
    }//GEN-LAST:event_MnRdbNegritasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MNbarra;
    private javax.swing.JMenuItem MnCerrar;
    private javax.swing.JMenuItem MnCopiar;
    private javax.swing.JMenuItem MnCortar;
    private javax.swing.JMenuItem MnIAbrir;
    private javax.swing.JMenuItem MnIArchivo1;
    private javax.swing.JMenuItem MnIarchivo2;
    private javax.swing.JRadioButtonMenuItem MnRdbNegritas;
    private javax.swing.JMenu MnReciente;
    private javax.swing.JMenu Mnacrhivo;
    private javax.swing.JMenu Mnediccion;
    private javax.swing.JMenuItem Mnpegar;
    private javax.swing.JTextField TXTSeleccioon;
    // End of variables declaration//GEN-END:variables
}
