/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elementosvisuales;

/**
 *
 * @author jorge
 */
public class Otra extends javax.swing.JFrame {
   private  String carrera  = " ";  
    private   String turno = " ";  
     
    public Otra() {
        initComponents();
           
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngCarreras = new javax.swing.ButtonGroup();
        btngturno = new javax.swing.ButtonGroup();
        rdbids = new javax.swing.JRadioButton();
        rdbidsi = new javax.swing.JRadioButton();
        lbseleccion = new javax.swing.JLabel();
        txtseleccion = new javax.swing.JTextField();
        rdbMec = new javax.swing.JRadioButton();
        rdbInd = new javax.swing.JRadioButton();
        lblturno = new javax.swing.JLabel();
        rdbMatutino = new javax.swing.JRadioButton();
        rdbVespertino = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btngCarreras.add(rdbids);
        rdbids.setText("IDS");
        rdbids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbidsActionPerformed(evt);
            }
        });

        btngCarreras.add(rdbidsi);
        rdbidsi.setText("IDSI");
        rdbidsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbidsiActionPerformed(evt);
            }
        });

        lbseleccion.setText("selecciona tu carrera");

        txtseleccion.setText(" ");
        txtseleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseleccionActionPerformed(evt);
            }
        });

        btngCarreras.add(rdbMec);
        rdbMec.setText("mecatronica");
        rdbMec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMecActionPerformed(evt);
            }
        });

        btngCarreras.add(rdbInd);
        rdbInd.setText("industrial");
        rdbInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbIndActionPerformed(evt);
            }
        });

        lblturno.setText("selecciona el  turno");

        btngturno.add(rdbMatutino);
        rdbMatutino.setText("matutino");
        rdbMatutino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMatutinoActionPerformed(evt);
            }
        });

        btngturno.add(rdbVespertino);
        rdbVespertino.setText("vespertino");
        rdbVespertino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbVespertinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbids)
                                .addGap(57, 57, 57)
                                .addComponent(rdbidsi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbMec)
                                .addGap(9, 9, 9)
                                .addComponent(rdbInd))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbVespertino)
                            .addComponent(rdbMatutino)
                            .addComponent(txtseleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblturno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbseleccion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbids)
                    .addComponent(rdbidsi))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbMec)
                    .addComponent(rdbInd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblturno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbMatutino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbVespertino)
                .addGap(20, 20, 20)
                .addComponent(txtseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbidsActionPerformed
           
        if(rdbids.isSelected()){
        carrera = "ids";
                  txtseleccion.setText(   carrera +  "el turno es " +turno );  

    } 
    }//GEN-LAST:event_rdbidsActionPerformed

    private void rdbidsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbidsiActionPerformed
     
        if(rdbidsi.isSelected()){
        carrera="idsi";
                 txtseleccion.setText(   carrera +  "el turno es " +turno );  

    } 
  
    }//GEN-LAST:event_rdbidsiActionPerformed

    private void rdbMecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMecActionPerformed
          if( rdbMec.isSelected()){
   carrera = "mecatronica";
            txtseleccion.setText(   carrera +  "el turno es " +turno );  

          }  
    }//GEN-LAST:event_rdbMecActionPerformed

    private void rdbIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbIndActionPerformed
           if(  rdbInd.isSelected()){
       carrera = "industrial";}
                    txtseleccion.setText(   carrera +  "el turno es " +turno );  

    }//GEN-LAST:event_rdbIndActionPerformed

    private void rdbVespertinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbVespertinoActionPerformed
      
        if(   rdbVespertino.isSelected()){ 
            turno ="vespertino ";
         txtseleccion.setText(   carrera +  "el turno es " +turno );  
    }   
    }//GEN-LAST:event_rdbVespertinoActionPerformed

    private void rdbMatutinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMatutinoActionPerformed
       if(   rdbMatutino.isSelected()){
            turno = "matutino"; 
       txtseleccion.setText(   carrera + " el turno es "+ turno );  
    } else {
             txtseleccion.setText("."); 
       }
      
    }//GEN-LAST:event_rdbMatutinoActionPerformed

    private void txtseleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseleccionActionPerformed


         
    }//GEN-LAST:event_txtseleccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Otra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Otra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Otra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Otra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Otra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngCarreras;
    private javax.swing.ButtonGroup btngturno;
    private javax.swing.JLabel lblturno;
    private javax.swing.JLabel lbseleccion;
    private javax.swing.JRadioButton rdbInd;
    private javax.swing.JRadioButton rdbMatutino;
    private javax.swing.JRadioButton rdbMec;
    private javax.swing.JRadioButton rdbVespertino;
    private javax.swing.JRadioButton rdbids;
    private javax.swing.JRadioButton rdbidsi;
    private javax.swing.JTextField txtseleccion;
    // End of variables declaration//GEN-END:variables
}
